<?xml version="1.0" encoding="utf-8"?><Database Name="DB_HIKARI_HTO2022_VER2" Class="HTO_DataStoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.1.15;Initial Catalog=DB_HIKARI_HTO2022_VER2;Persist Security Info=True;User ID=hto2022" SettingsObjectName="HIKARI_HTO_VER2.Properties.Settings" SettingsPropertyName="DB_HIKARI_HTO2022_VER2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DataAutocomplete" Member="DataAutocompletes">
    <Type Name="DataAutocomplete">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_LogErr" Member="tbl_LogErrs">
    <Type Name="tbl_LogErr">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="TimeErr" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IP_Adress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tb_Batch" Member="Tb_Batches">
    <Type Name="Tb_Batch">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NumberImage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PathPicture" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Hit_E11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E31" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E32" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChiaUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CongKhaiBatch" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Usercreate" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserLC_1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UserLC_3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status_LC_1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status_LC_3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Export" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tb_AllData" Member="Tb_AllDatas">
    <Type Name="Tb_AllData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Batch" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Level_Image" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Content_E1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_E1" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateStart_E1" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateEnd_E1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Time_E1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content_E2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_E2" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateStart_E2" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateEnd_E2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Time_E2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Error_E1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Error_E2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Length_E1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Length_E2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content_Check" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_Check" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateStart_Check" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd_Check" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Time_Check" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content_LC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_LC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReadImageDESO_1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ReadImageDESO_2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LoaiPhieuE1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiPhieuE2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiPhieuCheck" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiPhieuLC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Submit_E1" Type="System.Boolean" DbType="Bit NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Submit_E2" Type="System.Boolean" DbType="Bit NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spBatch_GetBatch_FULL_v2" Method="spBatch_GetBatch_FULL_v2">
    <ElementType Name="spBatch_GetBatch_FULL_v2Result">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserCreate" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PathPicture" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ChiaUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CongKhaiBatch" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spLogErr_AddLogger_v2" Method="spLogErr_AddLogger_v2">
    <Parameter Name="errorContent" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="userName" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="IP_Adress" Parameter="iP_Adress" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spBatch_Checker_v2" Method="spBatch_Checker_v2">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="spBatch_Checker_v2Result">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDataAutocomplete_GetListAutoComplete_v2" Method="spDataAutocomplete_GetListAutoComplete_v2">
    <ElementType Name="spDataAutocomplete_GetListAutoComplete_v2Result">
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spBatch_GetBatchType_v2" Method="spBatch_GetBatchType_v2">
    <Parameter Name="batchID" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="spBatch_GetBatchType_v2Result">
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Get_ChiaUser_Batch_v2" Method="Get_ChiaUser_Batch_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="Get_ChiaUser_Batch_v2Result">
      <Column Name="ChiaUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spBatch_getListbatch_LC_v2" Method="spBatch_getListbatch_LC_v2">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="level_Image" Type="System.String" DbType="NVarChar(5)" />
    <ElementType Name="spBatch_getListbatch_LC_v2Result">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spData_Getinfo_Image_Check_v2" Method="spData_Getinfo_Image_Check_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="level_image" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="spData_Getinfo_Image_Check_v2Result">
      <Column Name="[Số phiếu check]" Member="Số_phiếu_check" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Số phiếu đã check]" Member="Số_phiếu_đã_check" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_Status_ViewChitiet_V2" Method="Admin_Status_ViewChitiet_V2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Admin_Status_ViewChitiet_V2Result">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Level_Image" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content_E1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_E1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Content_E2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_E2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Content_Check" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_Check" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Content_LC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_Status_GetListBacth" Method="Admin_Status_GetListBacth">
    <Parameter Name="Style_Batch" Parameter="style_Batch" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="Admin_Status_GetListBacthResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_Status" Method="Admin_Status">
    <Parameter Name="Style_Batch" Parameter="style_Batch" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ListBatch" Parameter="listBatch" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="Admin_StatusResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NumberImage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuCheck1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongPhieuCheck1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserLC_1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status_LC_1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Hit_E31" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E32" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuCheck3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongPhieuCheck3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserLC_3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status_LC_3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaytao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Export" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hoanthanh1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hoanthanh3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_GetListLC_Export" Method="Admin_GetListLC_Export">
    <Parameter Name="Style_Batch" Parameter="style_Batch" Type="System.String" DbType="NVarChar(5)" />
    <ElementType Name="Admin_GetListLC_ExportResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LC_Exit_Batch" Method="LC_Exit_Batch">
    <Parameter Name="ID_Batch" Parameter="iD_Batch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="status" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="level" Type="System.String" DbType="NVarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LC_Update_Info_LC" Method="LC_Update_Info_LC">
    <Parameter Name="ID_Batch" Parameter="iD_Batch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Time_LC" Parameter="time_LC" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Time_Start" Parameter="time_Start" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spBatch_AddBatch_v2" Method="spBatch_AddBatch_v2">
    <Parameter Name="BatchName" Parameter="batchName" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="PathPicture" Parameter="pathPicture" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Location" Parameter="location" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="NumberImage" Parameter="numberImage" Type="System.Int32" DbType="Int" />
    <Parameter Name="BatchType" Parameter="batchType" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ChiaUser" Parameter="chiaUser" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CongKhaiBatch" Parameter="congKhaiBatch" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserCreate" Parameter="userCreate" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="spBatch_AddBatch_v2Result">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Check_ViewImage_Back_Next" Method="Check_ViewImage_Back_Next">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Id_Img" Parameter="id_Img" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Status_Button" Parameter="status_Button" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Level_img" Parameter="level_img" Type="System.String" DbType="NVarChar(5)" />
    <ElementType Name="Check_ViewImage_Back_NextResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_Status_NEW" Method="Admin_Status_NEW">
    <Parameter Name="Style_Batch" Parameter="style_Batch" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ListBatch" Parameter="listBatch" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="Admin_Status_NEWResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NumberImage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuCheck1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongPhieuCheck1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserLC_1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status_LC_1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Hit_E31" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E32" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuCheck3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongPhieuCheck3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserLC_3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status_LC_3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaytao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Export" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hoanthanh1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hoanthanh3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_View_Status_V3" Method="Admin_View_Status_V3">
    <Parameter Name="Style_Batch" Parameter="style_Batch" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="ListBatch" Parameter="listBatch" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="Admin_View_Status_V3Result">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NumberImage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuCheck1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongPhieuCheck1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserLC_1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status_LC_1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Hit_E31" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hit_E32" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhieuCheck3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongPhieuCheck3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserLC_3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status_LC_3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaytao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Export" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Hoanthanh1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hoanthanh3" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spImage_GetImage_Input_Entry_v2" Method="spImage_GetImage_Input_Entry_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="LevelUser" Parameter="levelUser" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="ChiaUser" Parameter="chiaUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.String" DbType="NVarChar(5)" />
    <ElementType Name="spImage_GetImage_Input_Entry_v2Result">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cohieu1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cohieu2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name_Img" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="pair" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="content1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="content2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_Export_Data_V2" Method="Admin_Export_Data_V2">
    <Parameter Name="List_ID_Batch" Parameter="list_ID_Batch" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="Admin_Export_Data_V2Result">
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_Batch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ResultLC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Thang" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spEntry_GetListbatch_v3" Method="spEntry_GetListbatch_v3">
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ID_Batch" Parameter="iD_Batch" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="level_User" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="spEntry_GetListbatch_v3Result">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ChiaUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CountChiaUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountNoChiaUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spData_InsertData_ENTRY_v2" Method="spData_InsertData_ENTRY_v2">
    <Parameter Name="ID_Image_Data" Parameter="iD_Image_Data" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="BatchID" Parameter="batchID" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Data_Entry" Parameter="data_Entry" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Pair_Entry" Parameter="pair_Entry" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LenData_Entry" Parameter="lenData_Entry" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Data_Entry_Split" Parameter="data_Entry_Split" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="spData_InsertData_ENTRY_v2Result">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spBatch_XoaBatch_v2" Method="spBatch_XoaBatch_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name_Table" Parameter="name_Table" Type="System.String" DbType="NVarChar(150)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spBatch_UpdateBatchChiaUser_v2" Method="spBatch_UpdateBatchChiaUser_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spBatch_UpdateCongKhaiBatch_v2" Method="spBatch_UpdateCongKhaiBatch_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spData_CheckBatch_ChiaUser_v2" Method="spData_CheckBatch_ChiaUser_v2">
    <Parameter Name="Id_Batch" Parameter="id_Batch" Type="System.Int32" DbType="Int" />
    <ElementType Name="spData_CheckBatch_ChiaUser_v2Result">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spEntryGetListBatch_v4" Method="spEntryGetListBatch_v4">
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Batch" Parameter="iD_Batch" Type="System.Int32" DbType="Int" />
    <Parameter Name="level_User" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="spEntryGetListBatch_v4Result">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ChiaUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spCheck_GetLishCheck_v3" Method="spCheck_GetLishCheck_v3">
    <Parameter Name="Id_Batch" Parameter="id_Batch" Type="System.Int32" DbType="Int" />
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.Int32" DbType="Int" />
    <ElementType Name="spCheck_GetLishCheck_v3Result">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ChiaUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Hit_E11" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spEntryGetImage_v2" Method="spEntryGetImage_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="LevelUser" Parameter="levelUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="ChiaUser" Parameter="chiaUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.Int32" DbType="Int" />
    <ElementType Name="spEntryGetImage_v2Result">
      <Column Name="IDImage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pair" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Flast1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Flast2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameImage" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spData_GetInfo_MissImage_Entry_v2" Method="spData_GetInfo_MissImage_Entry_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="level_image" Type="System.Int32" DbType="Int" />
    <Parameter Name="lv_User" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="chiaUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="spData_GetInfo_MissImage_Entry_v2Result">
      <Column Name="[Tổng số phiếu]" Member="Tổng_số_phiếu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Số phiếu còn]" Member="Số_phiếu_còn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Số phiếu nhập]" Member="Số_phiếu_nhập" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spEntry_Submit_New_v3" Method="spEntry_Submit_New_v3">
    <Parameter Name="ID_Image_Data" Parameter="iD_Image_Data" Type="System.Int32" DbType="Int" />
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Data_Entry" Parameter="data_Entry" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Pair_Entry" Parameter="pair_Entry" Type="System.Int32" DbType="Int" />
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.Int32" DbType="Int" />
    <Parameter Name="LenData_Entry" Parameter="lenData_Entry" Type="System.Int32" DbType="Int" />
    <Parameter Name="Data_Entry_Split" Parameter="data_Entry_Split" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="spEntry_Submit_New_v3Result">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spData_GetImage_Check_v2" Method="spData_GetImage_Check_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="User" Parameter="user" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.Int32" DbType="Int" />
    <ElementType Name="spData_GetImage_Check_v2Result">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content_E1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_E1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Content_E2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName_E2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Check_Update_Image_Back" Method="Check_Update_Image_Back">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Image_Data" Parameter="iD_Image_Data" Type="System.Int32" DbType="Int" />
    <Parameter Name="Error_E1" Parameter="error_E1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Error_E2" Parameter="error_E2" Type="System.Int32" DbType="Int" />
    <Parameter Name="Data_Submit" Parameter="data_Submit" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.Int32" DbType="Int" />
    <Parameter Name="TimeCheckUp" Parameter="timeCheckUp" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spData_Submit_Check_v2" Method="spData_Submit_Check_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_Image_Data" Parameter="iD_Image_Data" Type="System.Int32" DbType="Int" />
    <Parameter Name="Error_E1" Parameter="error_E1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Error_E2" Parameter="error_E2" Type="System.Int32" DbType="Int" />
    <Parameter Name="Data_Submit" Parameter="data_Submit" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Level_Image" Parameter="level_Image" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LC_spData_Getdata" Method="LC_spData_Getdata">
    <Parameter Name="ID_Batch" Parameter="iD_Batch" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Level_LC" Parameter="level_LC" Type="System.Int32" DbType="Int" />
    <ElementType Name="LC_spData_GetdataResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameImage" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Content_E1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content_E2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content_Check" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content_LC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_return_Role_image_v2" Method="Admin_return_Role_image_v2">
    <Parameter Name="Style_Role" Parameter="style_Role" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ImageID" Parameter="imageID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Level_image" Parameter="level_image" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spAdmin_Pfm_Entry" Method="spAdmin_Pfm_Entry">
    <Parameter Name="style_Pfm" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Time_Start" Parameter="time_Start" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Time_End" Parameter="time_End" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spAdmin_Pfm_EntryResult">
      <Column Name="ID_Batch" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Time_Entry" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Error_Entry" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LoaiNhap" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LenDong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spData_Refresh_Image_Entry_Check_v2" Method="spData_Refresh_Image_Entry_Check_v2">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LevelUser" Parameter="levelUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdData" Parameter="idData" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Admin_Pfm_Checker" Method="Admin_Pfm_Checker">
    <Parameter Name="Time_Start" Parameter="time_Start" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Time_End" Parameter="time_End" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="Admin_Pfm_CheckerResult">
      <Column Name="ID_Batch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TimeCheck" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Admin_Export_Data" Method="Admin_Export_Data">
    <Parameter Name="ListIDBatch" Parameter="listIDBatch" Type="System.String" DbType="NVarChar(500)" />
    <ElementType Name="Admin_Export_DataResult">
      <Column Name="IDImg" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ID_Batch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ResultLC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Loai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PathPicture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Entry_Check_ReturnBack_Image" Method="Entry_Check_ReturnBack_Image">
    <Parameter Name="BatchID" Parameter="batchID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_image" Parameter="iD_image" Type="System.Int32" DbType="Int" />
    <Parameter Name="Pair_Entry" Parameter="pair_Entry" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="Entry_Check_ReturnBack_ImageResult">
      <Column Name="ColumnData" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>